language: cpp
compiler: gcc
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install zip unzip mercurial g++ make autoconf2.13 yasm libgtk2.0-dev libglib2.0-dev libdbus-1-dev libdbus-glib-1-dev libasound2-dev libcurl4-openssl-dev libiw-dev libxt-dev mesa-common-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libpulse-dev"
script: "./build-no-xul.sh"
branches:
  only:
    - xul-9.0.1
notifications:
  email:
    on_success: change
    on_failure: change
  irc: "irc.mozilla.org#nightingale"
